/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
puppeteer.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_SERVER = 'residential-proxy.scrapeops.io';
const PROXY_PORT = '8181';
const PROXY_USERNAME = 'scrapeops';
const PROXY_PASSWORD = API_KEY;

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://www.decathlon.com";
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD"
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const parsePrice = (priceText) => {
            const cleanText = priceText.replace(/,/g, "");
            const match = cleanText.match(/[\d,]+\.?\d*/);
            return match ? parseFloat(match[0]) : 0.0;
        };

        const isValidCategory = (name) => {
            if (!name) return false;
            const clean = name.toLowerCase().trim();
            const blacklist = ["", "all", "shop all", "home", "sports", "men", "women", "kids", "view all", "filter:"];
            return !blacklist.includes(clean);
        };

        const extractJSONData = () => {
            let result = null;
            $("script[type='application/ld+json']").each((i, el) => {
                try {
                    const data = JSON.parse($(el).text());
                    if (data && typeof data === 'object') result = data;
                } catch (e) {}
            });
            if (!result) {
                try {
                    const headerJson = $("script#header-json").text();
                    if (headerJson) result = JSON.parse(headerJson);
                } catch (e) {}
            }
            return result;
        };

        const jsonData = extractJSONData();
        const outputData = {
            appliedFilters: [],
            timestamp: new Date().toISOString()
        };

        // Banner Image
        const ogImage = $("meta[property='og:image']").attr("content");
        outputData.bannerImage = ogImage ? makeAbsoluteURL(ogImage) : "";

        // Breadcrumbs
        const breadcrumbs = [];
        $(".dkt-breadcrumbs-bar__item a").each((i, el) => {
            const name = $(el).text().trim();
            const href = $(el).attr("href");
            if (name) {
                breadcrumbs.push({
                    name: name,
                    url: makeAbsoluteURL(href)
                });
            }
        });
        outputData.breadcrumbs = breadcrumbs;

        // Category ID
        outputData.categoryId = jsonData?.id || "";

        // Category Name
        let catName = "";
        // Strategy 1: header-json
        if (jsonData?.title && isValidCategory(jsonData.title)) {
            catName = jsonData.title.trim();
        }
        // Strategy 2: Hero H1
        if (!isValidCategory(catName)) {
            const h1Hero = $("h1.collection-hero__title").first().text().trim();
            if (isValidCategory(h1Hero)) catName = h1Hero;
        }
        // Strategy 3: Page Title
        if (!isValidCategory(catName)) {
            const pageTitle = $("title").first().text();
            if (pageTitle) {
                const parts = pageTitle.split(/[\u2013|\u2014|\-]/);
                const potentialName = parts[0].trim();
                if (isValidCategory(potentialName)) catName = potentialName;
            }
        }
        // Strategy 4: Active Nav
        if (!isValidCategory(catName)) {
            const activeNav = $(".plp-menu-nav__button--active").first().text().trim();
            if (isValidCategory(activeNav)) catName = activeNav;
        }
        // Strategy 5: Breadcrumbs last item
        if (!isValidCategory(catName)) {
            const items = $("main .dkt-breadcrumbs-bar__item, .breadcrumb__item, .breadcrumbs a");
            if (items.length > 0) {
                const lastItem = items.last().text().trim();
                if (isValidCategory(lastItem)) catName = lastItem;
            }
        }
        outputData.categoryName = catName;

        // Category URL
        let catURL = "";
        const canonical = $("link[rel='canonical']").attr("href");
        if (canonical) {
            catURL = makeAbsoluteURL(canonical);
        } else if (jsonData?.url) {
            let finalURL = jsonData.url;
            if (jsonData.id && !finalURL.includes("collection=")) {
                finalURL += (finalURL.includes("?") ? "&" : "?") + "collection=" + jsonData.id;
            }
            catURL = makeAbsoluteURL(finalURL);
        } else {
            const ogUrl = $("meta[property='og:url']").attr("content");
            if (ogUrl) catURL = makeAbsoluteURL(ogUrl);
        }
        outputData.categoryUrl = catURL;

        // Description
        outputData.description = $("meta[name='description']").attr("content") || "";

        // Pagination
        let totalRes = 0;
        const countText = $("#ProductCountDesktop").first().text();
        const countMatch = countText.match(/(\d+)/);
        if (countMatch) totalRes = parseInt(countMatch[1]);
        outputData.pagination = {
            currentPage: 1,
            nextPageUrl: null,
            prevPageUrl: null,
            resultsPerPage: null,
            totalPages: 1,
            totalResults: totalRes
        };

        // Products
        const products = [];
        $("li.grid__item").each((i, el) => {
            const s = $(el);
            const p = {
                availability: "in_stock",
                isPrime: false,
                isSponsored: false,
                preDiscountPrice: null
            };

            const brand = s.find(".font-body-s").first().text().trim();
            p.brand = brand || "Quechua";
            
            const priceText = s.find(".price-item--regular").first().text().trim();
            p.currency = detectCurrency(priceText);
            p.price = parsePrice(priceText);

            const img = s.find("img").first().attr("src");
            p.image = img ? makeAbsoluteURL(img) : "";

            const nameEl = s.find(".card__heading a").first();
            p.name = nameEl.text().trim();
            const pLink = nameEl.attr("href");
            p.url = makeAbsoluteURL(pLink);

            // Product ID Extraction
            let pID = "";
            const dataId = s.find("[data-product-id]").attr("data-product-id");
            if (dataId && dataId.length >= 13) {
                pID = dataId;
            } else {
                const htmlStr = s.html();
                const eanMatch = htmlStr.match(/\b(69|77|88)\d{11}\b/) || htmlStr.match(/\b\d{13}\b/);
                if (eanMatch) {
                    pID = eanMatch[0];
                } else {
                    const altText = s.find("img").first().attr("alt") || "";
                    const modelMatch = altText.match(/(\d{7,})/);
                    if (modelMatch) {
                        pID = modelMatch[1];
                    } else if (pLink) {
                        const parts = pLink.split("-");
                        pID = parts[parts.length - 1];
                    }
                }
            }
            p.productId = pID;

            // Rating
            let ratingVal = 0.0;
            const ratingText = s.find(".rating").first().attr("aria-label") || "";
            const rMatch = ratingText.match(/([\d\.]+) out of 5/);
            if (rMatch) {
                ratingVal = parseFloat(rMatch[1]);
            } else {
                ratingVal = parsePrice(s.find(".rating span").first().text());
            }
            p.rating = ratingVal;

            // Review Count
            let reviewCount = 0;
            let countRaw = s.find(".rating-count").text() || "";
            if (!countRaw) {
                s.find(".rating span").each((idx, span) => {
                    const txt = $(span).text();
                    if (txt.includes("(")) countRaw = txt;
                });
            }
            const countRegexMatch = countRaw.match(/\(\s*([\d,]+)\s*\)/);
            if (countRegexMatch) {
                reviewCount = parseInt(countRegexMatch[1].replace(/,/g, ""));
            } else {
                const nums = countRaw.match(/[\d,]+/g) || [];
                let maxVal = 0;
                nums.forEach(n => {
                    if (!n.includes(".")) {
                        const val = parseInt(n.replace(/,/g, ""));
                        if (val > maxVal) maxVal = val;
                    }
                });
                reviewCount = maxVal;
            }
            p.reviewCount = reviewCount;

            products.push(p);
        });
        outputData.products = products;

        // Subcategories
        const subcats = [];
        $(".plp-menu-nav__button").each((i, el) => {
            const name = $(el).text().trim();
            const anchor = name.toLowerCase().replace(/\s+/g, "-");
            subcats.push({
                name: name,
                productCount: null,
                url: "https://www.decathlon.com#" + anchor
            });
        });
        outputData.subcategories = subcats;

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Puppeteer with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Puppeteer browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let page = null;
        
        try {
            page = await browser.newPage();
            
            await page.setViewport({ width: 1920, height: 1080 });
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36');
            
            await page.setRequestInterception(true);
            page.on('request', (request) => {
                const resourceType = request.resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    request.abort();
                } else {
                    request.continue();
                }
            });
            
            await page.authenticate({
                username: PROXY_USERNAME,
                password: PROXY_PASSWORD
            });
            
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Replicating Sleep/Wait
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            const bodyHTML = await page.content();
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    const browser = await puppeteer.launch({
        headless: 'new',
        ignoreHTTPSErrors: true,
        args: [
            `--proxy-server=http://${PROXY_SERVER}:${PROXY_PORT}`,
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/collections/lifestyle-packs?collection=12110',
    ];

    console.log('Starting concurrent scraping with NodeJS Puppeteer-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };