/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const { chromium } = require('playwright-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
chromium.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_CONFIG = {
    server: 'http://residential-proxy.scrapeops.io:8181',
    username: 'scrapeops',
    password: API_KEY
};

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const domain = "https://www.decathlon.com";

        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const stripHTML = (s) => {
            return s.replace(/<[^>]*>/g, ' ').trim();
        };

        const detectCurrency = (priceText) => {
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const cleanNumeric = (s) => {
            const match = s.match(/[\d,]+\.?\d*/);
            if (match) {
                return parseFloat(match[0].replace(/,/g, ''));
            }
            return 0;
        };

        let jsonLD = null;
        $("script[type='application/ld+json']").each((i, el) => {
            try {
                const data = JSON.parse($(el).text());
                if (data["@type"] === "Product" || data["@type"] === "ItemList") {
                    jsonLD = data;
                }
            } catch (e) {}
        });

        const outputData = {};
        outputData.jsonLD = jsonLD;
        outputData.appliedFilters = [];

        let bannerImg = "";
        const ogImg = $("meta[property='og:image']").attr("content");
        if (ogImg) bannerImg = makeAbsoluteURL(ogImg);
        outputData.bannerImage = bannerImg;

        const breadcrumbs = [];
        $(".plp-menu-nav__back-button, .breadcrumb a").each((i, el) => {
            const name = $(el).text().trim();
            const href = $(el).attr("href");
            if (name) {
                breadcrumbs.push({
                    name: name,
                    url: makeAbsoluteURL(href)
                });
            }
        });
        outputData.breadcrumbs = breadcrumbs;

        let catId = "";
        const canonicalUrl = $("link[rel='canonical']").attr("href");
        if (canonicalUrl) {
            const match = canonicalUrl.match(/collection=(\d+)/);
            if (match && match[1]) catId = match[1];
        }
        outputData.categoryId = catId;

        let catName = $("h1.collection-hero__title").first().text().trim();
        if (!catName) {
            catName = $("title").first().text().split("–")[0].trim();
        }
        catName = catName.replace(/^Collection:\s+/, "").trim();
        outputData.categoryName = catName;
        outputData.categoryUrl = makeAbsoluteURL(canonicalUrl || "");

        let desc = $("meta[name='description']").attr("content");
        if (!desc) {
            desc = stripHTML($(".accordion__content").first().text());
        }
        outputData.description = desc;

        let totalResults = 0;
        const resText = $("#ProductCountDesktop, .product-count__text").first().text();
        const resMatch = resText.match(/(\d+)/);
        if (resMatch) totalResults = parseInt(resMatch[1]);
        
        outputData.pagination = {
            currentPage: null,
            nextPageUrl: null,
            prevPageUrl: null,
            resultsPerPage: null,
            totalPages: null,
            totalResults: totalResults,
        };

        const products = [];
        $("li.grid__item").each((i, el) => {
            const s = $(el);
            const pName = s.find(".card__heading a, .full-unstyled-link").first().text().trim();
            if (!pName) return;

            const pUrl = s.find("a.full-unstyled-link").first().attr("href") || "";
            const pPriceText = s.find(".price-item--regular, .price").first().text();
            const pPrice = cleanNumeric(pPriceText);
            
            let pImg = s.find("img").first().attr("src") || s.find("img").first().attr("data-src") || "";

            let pRating = 0.0;
            let pRatingText = s.find(".rating").first().attr("aria-label") || s.find(".rating-text").first().text();
            const ratMatch = pRatingText.match(/(\d+\.?\d*)/);
            if (ratMatch) pRating = parseFloat(ratMatch[1]);

            let pReviews = 0;
            const pRevText = s.find(".rating-count").first().text();
            const revMatch = pRevText.match(/(\d[\d,]+)/);
            if (revMatch) pReviews = parseInt(revMatch[1].replace(/,/g, ''));

            let pId = "";
            const idSelector = s.find(".card__heading, .card__heading a").filter((i, sel) => $(sel).attr("id")).first();
            const idAttr = idSelector.attr("id");
            if (idAttr) {
                const parts = idAttr.split("-");
                pId = parts[parts.length - 1];
            }

            if (!pId && pUrl) {
                const idMatch = pUrl.match(/-(\d+)$/);
                if (idMatch) pId = idMatch[1];
            }

            products.push({
                availability: "in_stock",
                brand: s.find(".font-body-s").first().text().trim(),
                currency: detectCurrency(pPriceText),
                image: makeAbsoluteURL(pImg.split("&")[0]),
                isPrime: false,
                isSponsored: false,
                name: pName,
                preDiscountPrice: null,
                price: pPrice,
                productId: pId,
                rating: pRating,
                reviewCount: pReviews,
                url: makeAbsoluteURL(pUrl),
            });
        });
        outputData.products = products;

        const subcats = [];
        const headerScript = $("#header-json").text();
        if (headerScript) {
            try {
                const navData = JSON.parse(headerScript);
                const findItems = (data) => {
                    if (data && typeof data === 'object') {
                        if (data.title) {
                            subcats.push({
                                name: data.title,
                                productCount: null,
                                url: makeAbsoluteURL(data.url || ""),
                            });
                        }
                        if (Array.isArray(data.children)) {
                            data.children.forEach(child => findItems(child));
                        }
                    }
                };
                findItems(navData);
            } catch (e) {}
        }

        if (subcats.length === 0) {
            $(".plp-menu-nav__button").each((i, el) => {
                subcats.push({
                    name: $(el).text().trim(),
                    productCount: null,
                    url: "",
                });
            });
        }
        outputData.subcategories = subcats;

        return {
            ...outputData,
            url: url,
            timestamp: new Date().toISOString()
        };
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Playwright with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Playwright browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let context = null;
        let page = null;
        
        try {
            // Create context with optimizations
            context = await browser.newContext({
                ignoreHTTPSErrors: true,
                viewport: { width: 1920, height: 1080 },
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
            });
            
            page = await context.newPage();
            
            // Block unnecessary resources for performance optimization
            await page.route('**/*', (route) => {
                const resourceType = route.request().resourceType();
                if (['image', 'media', 'font'].includes(resourceType)) {
                    route.abort();
                } else {
                    route.continue();
                }
            });
            
            // Navigate with optimized wait strategy
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Wait for dynamic product grid items to load
            await page.waitForSelector('li.grid__item', { timeout: 15000 }).catch(() => {});
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            if (context) await context.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    // Launch browser with performance optimizations
    const browser = await chromium.launch({
        headless: true,
        proxy: PROXY_CONFIG,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        // Process URLs in batches to control concurrency
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/collections/lifestyle-packs?collection=12110',
    ];

    console.log('Starting concurrent scraping with NodeJS Playwright-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

// Run the scraper if this file is executed directly
if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };