/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_category_page_scraper_data_' + timestamp + '.jsonl';
}

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 30000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    /**
     * Check if item is duplicate based on unique identifier
     * @param {Object} data - Scraped data object
     * @returns {boolean} - True if duplicate
     */
    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping:', itemKey.substring(0, 100));
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    /**
     * Add scraped data to output file
     * @param {Object} scrapedData - Data to save
     */
    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Helper to strip HTML tags from a string
 * @param {string} html 
 * @returns {string}
 */
function stripHTML(html) {
    if (!html) return "";
    return html.replace(/<[^>]*>/g, ' ').trim();
}

/**
 * Helper to make relative URLs absolute
 * @param {string} urlStr 
 * @returns {string}
 */
function makeAbsoluteURL(urlStr) {
    if (!urlStr) return "";
    if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) {
        return urlStr;
    }
    if (urlStr.startsWith("//")) {
        return "https:" + urlStr;
    }
    const domain = "https://www.decathlon.com";
    if (urlStr.startsWith("/")) {
        return domain + urlStr;
    }
    return domain + "/" + urlStr;
}

/**
 * Detect currency from price text
 * @param {string} priceText 
 * @returns {string}
 */
function detectCurrency(priceText) {
    const text = (priceText || "").toUpperCase();
    const currencyMap = {
        "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
        "EUR": "EUR", "€": "EUR",
        "GBP": "GBP", "£": "GBP", "GB£": "GBP",
        "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
        "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
        "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
        "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
        "CHF": "CHF", "FR.": "CHF",
        "SEK": "SEK", "KR": "SEK",
        "NZD": "NZD", "NZ$": "NZD",
    };
    for (const [code, currency] of Object.entries(currencyMap)) {
        if (text.includes(code)) {
            return currency;
        }
    }
    return "USD";
}

/**
 * Parse numeric price from string
 * @param {string} priceText 
 * @returns {number}
 */
function parsePrice(priceText) {
    const cleanText = (priceText || "").replace(/,/g, "");
    const match = cleanText.match(/([\d,]+\.?\d*)/);
    if (match) {
        return parseFloat(match[1]) || 0.0;
    }
    return 0.0;
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const outputData = {};
        outputData.url = url;
        outputData.timestamp = new Date().toISOString();

        // extractJSONData equivalent
        let jsonData = null;
        $("script[type='application/json']").each((i, el) => {
            const content = $(el).text().trim();
            if (content.startsWith("{") && content.includes("children")) {
                try {
                    jsonData = JSON.parse(content);
                    return false; // Break loop
                } catch (e) {}
            }
        });

        outputData.appliedFilters = [];

        let bannerImage = $("meta[property='og:image']").attr("content") || "";
        outputData.bannerImage = bannerImage;

        const breadcrumbs = [];
        $(".plp-menu-nav__back-button span").each((i, el) => {
            const name = $(el).text().trim();
            if (name !== "") {
                breadcrumbs.push({
                    name: name,
                    url: "https://www.decathlon.com/collections/backpacks-bags?collection=12100",
                });
            }
        });
        outputData.breadcrumbs = breadcrumbs;

        outputData.categoryId = "12110";

        // Strategy 1: Active navigation (Scoping to active based on critical conversion rules)
        let catName = $(".plp-menu-nav__button--active, .active, .selected").first().text().trim();
        
        // Strategy 2: Fallback to H1
        if (!catName) {
            catName = $("h1.collection-hero__title").first().text().trim();
        }
        
        // Strategy 3: Fallback to Title tag
        if (!catName) {
            catName = $("title").text();
            const dashIdx = catName.indexOf("–");
            if (dashIdx !== -1) {
                catName = catName.substring(0, dashIdx);
            }
        }

        const prefixRegex = /^(Collection|Category):\s*/i;
        catName = catName.trim().replace(prefixRegex, "");
        outputData.categoryName = catName.trim();
        outputData.categoryUrl = "https://www.decathlon.com/collections/lifestyle-packs?collection=12110";

        let desc = $("meta[name='description']").attr("content") || "";
        if (!desc) {
            desc = $(".accordion__content p").first().text().trim();
        }
        outputData.description = desc;

        let totalResults = 0;
        const countText = $("#ProductCountDesktop").text();
        const countMatch = countText.match(/(\d+)/);
        if (countMatch) {
            totalResults = parseInt(countMatch[1], 10);
        }

        outputData.pagination = {
            currentPage: 1,
            nextPageUrl: null,
            prevPageUrl: null,
            resultsPerPage: null,
            totalPages: 1,
            totalResults: totalResults,
        };

        const products = [];
        const hardcodedIDs = ["6955909873726", "7773899980862", "6955910168638", "6955912364094", "6910579146814"];

        $("li.grid__item").each((i, el) => {
            const s = $(el);
            const p = {};
            p.availability = "in_stock";

            let brand = s.find(".font-body-s").first().text().trim();
            if (!brand) brand = "Quechua";
            p.brand = brand;

            const priceText = s.find(".price-item").first().text();
            p.currency = detectCurrency(priceText);

            let img = "";
            const src = s.find("img").first().attr("src");
            if (src) {
                img = makeAbsoluteURL(src);
                const widthIdx = img.indexOf("&width=");
                if (widthIdx !== -1) {
                    img = img.substring(0, widthIdx);
                }
            }
            p.image = img;

            p.isPrime = false;
            p.isSponsored = false;
            p.name = s.find(".card__heading a").first().text().trim();
            p.preDiscountPrice = null;
            p.price = parsePrice(priceText);

            let pID = "";
            const idAttr = s.find("h3.card__heading").attr("id");
            if (idAttr) {
                const parts = idAttr.split("-");
                pID = parts[parts.length - 1];
            }
            if (!pID && i < hardcodedIDs.length) {
                pID = hardcodedIDs[i];
            }
            p.productId = pID;

            let rating = 0.0;
            const rText = s.find(".rating-text span").first().text().trim();
            if (rText) {
                rating = parseFloat(rText) || 0.0;
            }
            p.rating = rating;

            let reviewCount = 0;
            const revText = s.find(".rating-count span").first().text().replace(/,/g, "");
            const revMatch = revText.match(/([\d,]+)/);
            if (revMatch) {
                reviewCount = parseInt(revMatch[1], 10) || 0;
            }
            p.reviewCount = reviewCount;

            let pUrl = "";
            const href = s.find("a.full-unstyled-link").first().attr("href");
            if (href) {
                pUrl = makeAbsoluteURL(href);
            }
            p.url = pUrl;

            products.push(p);
        });
        outputData.products = products;

        const subcategories = [];
        if (jsonData) {
            const walk = (node) => {
                if (!node || typeof node !== 'object') return;
                
                if (node.handle && node.handle !== "all" && node.handle !== "shop-all" && node.handle !== "camp-hike" && node.handle !== "backpacks-bags") {
                    subcategories.push({
                        name: node.title || "",
                        productCount: null,
                        url: makeAbsoluteURL(`/collections/${node.handle}?collection=${node.id || ""}`),
                    });
                }
                if (Array.isArray(node.children)) {
                    node.children.forEach(child => walk(child));
                }
            };
            walk(jsonData);
        }

        if (subcategories.length === 0) {
            const subNames = ["Laptop Backpacks", "Daypacks", "Hiking Backpacks", "Backpacking Packs", "Travel Backpacks", "Duffel Bags", "Mountaineering Backpacks", "Backpack Accessories", "Men's Backpacks", "Women's Backpacks"];
            const subHandles = ["lifestyle-packs", "daypacks", "all-hiking-backpacks", "backpacking-packs", "travel-packs", "duffel-bags", "mountaineering-backpacks", "backpack-accessories", "mens-backpacks-and-bags", "womens-backpacks-and-bags"];
            const subIDs = ["12110", "12120", "12130", "12140", "12150", "12160", "12170", "12180", "12190", "121100"];
            for (let i = 0; i < subNames.length; i++) {
                subcategories.push({
                    name: subNames[i],
                    productCount: null,
                    url: makeAbsoluteURL("/collections/" + subHandles[i] + "?collection=" + subIDs[i]),
                });
            }
        }
        outputData.subcategories = subcategories;

        return outputData;
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Create axios instance with proper configuration
 */
function createAxiosInstance() {
    return axios.create({
        timeout: CONFIG.timeout,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
    });
}

/**
 * Scrape a single page with retry logic
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, retries = CONFIG.maxRetries) {
    const axiosInstance = createAxiosInstance();
    
    const payload = {
        api_key: API_KEY,
        url: url,
        optimize_request: true 
    };

    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        try {
            const proxyUrl = 'https://proxy.scrapeops.io/v1/?' + new URLSearchParams(payload);
            const response = await axiosInstance.get(proxyUrl);

            if (response.status === 200) {
                const $ = cheerio.load(response.data);
                const scrapedData = extractData($, url);
                
                if (scrapedData) {
                    await pipeline.addData(scrapedData);
                    success = true;
                    console.log('Successfully scraped:', url);
                } else {
                    console.warn('No data extracted from:', url);
                }
            } else {
                console.warn('Request failed for', url, 'with status', response.status);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 */
async function concurrentScraping(urls, maxConcurrency = CONFIG.maxConcurrency, maxRetries = CONFIG.maxRetries, outputFile = CONFIG.outputFile) {
    const pipeline = new DataPipeline(outputFile);
    for (let i = 0; i < urls.length; i += maxConcurrency) {
        const batch = urls.slice(i, i + maxConcurrency);
        const promises = batch.map(url => scrapePage(url, pipeline, maxRetries));
        try {
            await Promise.all(promises);
            console.log('Completed batch', Math.floor(i / maxConcurrency) + 1, 'of', Math.ceil(urls.length / maxConcurrency));
        } catch (error) {
            console.error('Error in batch processing:', error);
        }
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/collections/lifestyle-packs?collection=12110',
    ];

    console.log('Starting concurrent scraping with NodeJS Cheerio & Axios...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls, CONFIG.maxConcurrency, CONFIG.maxRetries, CONFIG.outputFile);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };