/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_search_page_scraper_data_' + timestamp + '.jsonl';
}

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 30000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    /**
     * Check if item is duplicate based on unique identifier
     * @param {Object} data - Scraped data object
     * @returns {boolean} - True if duplicate
     */
    isDuplicate(data) {
        const itemKey = data.productId || JSON.stringify(data.name + data.url);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping:', String(itemKey).substring(0, 100));
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    /**
     * Add scraped data to output file
     * @param {Object} scrapedData - Data to save
     */
    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} baseUrl - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, baseUrl) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            const domain = "https://www.decathlon.com";
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const parsePrice = (priceText) => {
            if (!priceText) return 0.0;
            const cleanText = priceText.replace(/,/g, '');
            const match = cleanText.match(/[\d,]+\.?\d*/);
            return match ? parseFloat(match[0]) : 0.0;
        };

        const productList = [];
        $(".grid__item, .rebuy-product-block").each((i, el) => {
            const s = $(el);
            
            // Name extraction targeting active links
            let name = s.find(".card__heading a, .rebuy-product-title-link").first().text().trim();
            if (!name) return;

            let priceVal = 0.0;
            let preDiscountVal = 0.0;
            let currency = "USD";

            const priceContainer = s.find(".price, .rebuy-product-price").first();
            if (priceContainer.length > 0) {
                currency = detectCurrency(priceContainer.text());
                const salePrice = priceContainer.find(".price-item--sale, .rebuy-money").first();
                priceVal = salePrice.length > 0 ? parsePrice(salePrice.text()) : parsePrice(priceContainer.text());

                const regPrice = priceContainer.find(".price-item--regular").last();
                if (regPrice.length > 0) {
                    const parsedReg = parsePrice(regPrice.text());
                    if (parsedReg > priceVal && priceVal > 0) {
                        preDiscountVal = parsedReg;
                    }
                }
            }

            let url = "";
            const urlEl = s.find("a.full-unstyled-link, a.rebuy-product-title-link").first();
            if (urlEl.length > 0) {
                url = makeAbsoluteURL(urlEl.attr("href"));
            }

            let pID = "";
            s.find("h3.card__heading, [id*='Badge--'], [id*='title--']").each((idx, sel) => {
                if (pID !== "") return;
                const idAttr = $(sel).attr("id") || "";
                const match = idAttr.match(/\d+/);
                if (match && match[0].length >= 10) {
                    pID = match[0];
                }
            });

            let brand = s.find(".font-body-s").first().text().trim();
            if (!brand) brand = "Quechua";

            const images = [];
            const imgSel = s.find("img").first();
            if (imgSel.length > 0) {
                images.push({
                    altText: imgSel.attr("alt") || "",
                    url: makeAbsoluteURL(imgSel.attr("src"))
                });
            }

            let ratingVal = 0.0;
            let reviewCount = 0;
            const ratingContainer = s.find(".rating").first();
            const ariaLabel = ratingContainer.attr("aria-label") || "";

            if (ariaLabel) {
                const match = ariaLabel.match(/(\d+\.?\d*)/);
                if (match) ratingVal = parseFloat(match[0]);
            }
            if (ratingVal === 0.0) {
                const textVal = s.find(".rating-text").text();
                const match = textVal.match(/(\d+\.?\d*)/);
                if (match) ratingVal = parseFloat(match[0]);
            }

            const countSel = s.find(".rating-count").first();
            let countText = countSel.length > 0 ? countSel.text() : (ariaLabel.includes("reviews") || ariaLabel.includes("stars") ? ariaLabel : "");

            if (countText) {
                const matches = countText.match(/([\d,]+)/g) || [];
                for (const m of matches) {
                    if (m.includes(".")) continue;
                    const clean = m.replace(/,/g, '');
                    const val = parseInt(clean, 10);
                    if (!isNaN(val)) {
                        reviewCount = val;
                        break;
                    }
                }
            }

            const badges = [];
            const promotions = [];
            s.find(".badge, .card__badge span.badge").each((j, bEl) => {
                const label = $(bEl).text().trim();
                if (!label) return;
                badges.push({ label, type: "deal" });

                if (label.includes("%")) {
                    const match = label.match(/(\d+)/);
                    if (match) {
                        promotions.push({
                            description: label,
                            discountPercentage: parseInt(match[0], 10),
                            type: "percentage_off"
                        });
                    }
                }
            });

            const visibleOptions = [];
            s.find(".card_swatches .swatch").each((j, swEl) => {
                const sw = $(swEl);
                const title = sw.attr("data-variant-title");
                const imgSrc = sw.attr("data-variant-image-src");
                if (title) {
                    const option = { type: "color/size", value: title };
                    if (imgSrc) option.imageUrl = makeAbsoluteURL(imgSrc);
                    visibleOptions.push(option);
                }
            });

            const variants = {
                variantCount: visibleOptions.length > 0 ? visibleOptions.length : 1,
                visibleOptions: visibleOptions
            };

            productList.push({
                aggregateRating: {
                    bestRating: 5,
                    ratingValue: ratingVal,
                    reviewCount: reviewCount,
                    worstRating: 1
                },
                availability: "in_stock",
                badges,
                brand,
                category: null,
                currency,
                description: "",
                images,
                name,
                preDiscountPrice: preDiscountVal,
                price: priceVal,
                productId: pID,
                promotions,
                seller: {
                    name: "Decathlon",
                    rating: 0,
                    url: "https://www.decathlon.com"
                },
                url,
                variants
            });
        });

        const related = [];
        $(".rebuy-product-block").each((i, el) => {
            const s = $(el);
            const rName = s.find(".rebuy-product-title").text().trim();
            const rPrice = parsePrice(s.find(".rebuy-money").text());
            const rUrl = s.find("a").attr("href");
            const rImg = s.find("img").attr("src");
            if (rName) {
                related.push({
                    currency: "USD",
                    imageUrl: makeAbsoluteURL(rImg),
                    name: rName,
                    price: rPrice,
                    url: makeAbsoluteURL(rUrl)
                });
            }
        });

        const countText = $("#ProductCountDesktop").text();
        const totalMatch = countText.match(/\d+/);
        const totalResults = totalMatch ? parseInt(totalMatch[0], 10) : 0;

        return {
            breadcrumbs: [],
            pagination: null,
            products: productList,
            recommendations: { relatedProducts: related },
            relatedSearches: [],
            searchMetadata: {
                query: $("input.search__input").attr("value") || "kids shoes",
                resultsDisplayed: productList.length,
                searchType: "keyword",
                searchUrl: baseUrl,
                totalResults: totalResults
            },
            sponsoredProducts: []
        };
    } catch (error) {
        console.error('Error extracting data from', baseUrl, ':', error);
        return null;
    }
}

/**
 * Create axios instance with proper configuration
 */
function createAxiosInstance() {
    return axios.create({
        timeout: CONFIG.timeout,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
    });
}

/**
 * Scrape a single page with retry logic
 */
async function scrapePage(url, pipeline, retries = CONFIG.maxRetries) {
    const axiosInstance = createAxiosInstance();
    const payload = {
        api_key: API_KEY,
        url: url,
        optimize_request: true 
    };

    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        try {
            const proxyUrl = 'https://proxy.scrapeops.io/v1/?' + new URLSearchParams(payload);
            const response = await axiosInstance.get(proxyUrl);

            if (response.status === 200) {
                const $ = cheerio.load(response.data);
                const scrapedData = extractData($, url);
                
                if (scrapedData) {
                    await pipeline.addData(scrapedData);
                    success = true;
                    console.log('Successfully scraped:', url);
                } else {
                    console.warn('No data extracted from:', url);
                }
            } else {
                console.warn('Request failed for', url, 'with status', response.status);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently
 */
async function concurrentScraping(urls, maxConcurrency = CONFIG.maxConcurrency, maxRetries = CONFIG.maxRetries, outputFile = CONFIG.outputFile) {
    const pipeline = new DataPipeline(outputFile);
    
    for (let i = 0; i < urls.length; i += maxConcurrency) {
        const batch = urls.slice(i, i + maxConcurrency);
        const promises = batch.map(url => scrapePage(url, pipeline, maxRetries));
        
        try {
            await Promise.all(promises);
            console.log('Completed batch', Math.floor(i / maxConcurrency) + 1, 'of', Math.ceil(urls.length / maxConcurrency));
        } catch (error) {
            console.error('Error in batch processing:', error);
        }
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/search?q=kids+shoes&options%5Bprefix%5D=last',
    ];

    console.log('Starting concurrent scraping with NodeJS Cheerio & Axios...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls, CONFIG.maxConcurrency, CONFIG.maxRetries, CONFIG.outputFile);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };