/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const { chromium } = require('playwright-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
chromium.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_search_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_CONFIG = {
    server: 'http://residential-proxy.scrapeops.io:8181',
    username: 'scrapeops',
    password: API_KEY
};

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            const domain = "https://www.decathlon.com";
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const extractPrice = (priceText) => {
            const cleanText = priceText.replace(/,/g, "");
            const match = cleanText.match(/[\d,]+\.?\d*/);
            return match ? parseFloat(match[0]) : 0;
        };

        const productList = [];
        const seenIDs = new Set();

        $(".grid__item").each((i, el) => {
            const s = $(el);
            let name = "";
            const nameSelectors = [".card__heading a", "h3.card__heading", ".full-unstyled-link"];
            for (const sel of nameSelectors) {
                const val = s.find(sel).first().text().trim();
                if (val) {
                    name = val;
                    break;
                }
            }
            if (!name) return;

            let pURL = "";
            const href = s.find("a.full-unstyled-link").first().attr("href");
            if (href) pURL = makeAbsoluteURL(href);

            let pID = "";
            const idAttr = s.find(".card__heading a").first().attr("id") || s.find(".card__heading").first().attr("id");
            if (idAttr) {
                const parts = idAttr.split("--");
                if (parts.length > 1) pID = parts[parts.length - 1];
            }

            if (pID) {
                if (seenIDs.has(pID)) return;
                seenIDs.add(pID);
            }

            let brand = "Quechua";
            const bVal = s.find(".font-body-s").first().text().trim();
            if (bVal) brand = bVal;

            let priceVal = 0.0;
            let prePriceVal = null;
            let currency = "USD";

            const priceBox = s.find(".price").first();
            if (priceBox.length > 0) {
                currency = detectCurrency(priceBox.text());
                const isOnSale = priceBox.hasClass("price--on-sale");

                if (isOnSale) {
                    const salePriceElem = priceBox.find(".price__sale .price-item--sale").first();
                    const regPriceElem = priceBox.find(".price__sale .price-item--regular").first();
                    
                    if (salePriceElem.length > 0) {
                        priceVal = extractPrice(salePriceElem.text());
                    }
                    if (regPriceElem.length > 0) {
                        const originalPrice = extractPrice(regPriceElem.text());
                        if (originalPrice > 0 && originalPrice !== priceVal) {
                            prePriceVal = originalPrice;
                        }
                    }
                } else {
                    const regPriceElem = priceBox.find(".price__regular .price-item--regular").first();
                    if (regPriceElem.length > 0) {
                        priceVal = extractPrice(regPriceElem.text());
                    }
                }
            }

            const images = [];
            s.find("img").each((j, imgEl) => {
                const imgSel = $(imgEl);
                let src = imgSel.attr("src");
                if (src) {
                    let cleanURL = src.split("&width=")[0].split("?width=")[0];
                    images.push({
                        altText: imgSel.attr("alt") || "",
                        url: makeAbsoluteURL(cleanURL)
                    });
                }
            });

            let ratingVal = 0.0;
            let reviewCount = 0;
            const ratingText = s.find(".rating").first().attr("aria-label") || "";
            if (ratingText) {
                const matchR = ratingText.match(/(\d+\.?\d*)/);
                if (matchR) ratingVal = parseFloat(matchR[0]);
            }
            if (ratingVal === 0) {
                ratingVal = parseFloat(s.find(".rating-text span").first().text().trim()) || 0;
            }

            const countText = s.find(".rating-count span").first().text().replace(/,/g, "");
            const matchC = countText.match(/[\d,]+/);
            if (matchC) reviewCount = parseInt(matchC[0], 10);

            const badges = [];
            const seenBadges = new Set();
            s.find(".badge").each((k, bEl) => {
                const label = $(bEl).text().trim();
                if (label && !seenBadges.has(label)) {
                    seenBadges.add(label);
                    badges.push({ label, type: "deal" });
                }
            });

            const visibleOptions = [];
            s.find(".swatch").each((l, swEl) => {
                const swSel = $(swEl);
                const vTitle = swSel.attr("data-variant-title") || "";
                const vImg = swSel.attr("data-variant-image-src") || "";
                let colorVal = "";
                if (vTitle) {
                    colorVal = vTitle.split("/")[0].trim();
                }
                visibleOptions.push({
                    imageUrl: makeAbsoluteURL(vImg),
                    type: "color",
                    value: colorVal
                });
            });

            const pData = {
                aggregateRating: {
                    bestRating: 5,
                    ratingValue: ratingVal,
                    reviewCount: reviewCount,
                    worstRating: 1,
                },
                availability: "in_stock",
                badges: badges,
                brand: brand,
                currency: currency,
                description: "",
                features: [],
                images: images,
                name: name,
                preDiscountPrice: prePriceVal,
                price: priceVal,
                productId: pID,
                reviews: [],
                seller: {
                    name: "Decathlon",
                    rating: 0,
                    url: "https://www.decathlon.com",
                },
                serialNumbers: [],
                specifications: [],
                url: pURL,
                videos: [],
                variants: {
                    variantCount: visibleOptions.length,
                    visibleOptions: visibleOptions,
                },
            };

            if (badges.length > 0) {
                pData.promotions = badges.map(b => {
                    const matchP = b.label.match(/(\d+)/);
                    return {
                        description: b.label,
                        discountPercentage: matchP ? parseInt(matchP[0], 10) : 0,
                        type: "discount"
                    };
                });
            }

            productList.push(pData);
        });

        const searchTitle = $("input[name='q']").first().attr("value") || "kids shoes";
        let totalResults = 0;
        const totalText = $("#ProductCountDesktop").text();
        const matchT = totalText.match(/(\d+)/);
        if (matchT) totalResults = parseInt(matchT[0], 10);

        return {
            breadcrumbs: null,
            pagination: {
                currentPage: 1,
                hasNextPage: false,
                hasPreviousPage: false,
                nextPageUrl: null,
                previousPageUrl: null,
                totalPages: 1,
            },
            products: productList,
            recommendations: {
                relatedProducts: [],
            },
            relatedSearches: [],
            searchMetadata: {
                query: searchTitle,
                resultsDisplayed: productList.length,
                searchType: "keyword",
                searchUrl: "https://www.decathlon.com/search?q=kids+shoes&options%5Bprefix%5D=last",
                totalResults: totalResults,
            },
        };
    } catch (error) {
        console.error('Error extracting data from', url, ':', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Playwright with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Playwright browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let context = null;
        let page = null;
        
        try {
            // Create context with optimizations
            context = await browser.newContext({
                ignoreHTTPSErrors: true,
                viewport: { width: 1920, height: 1080 },
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
            });
            
            page = await context.newPage();
            
            // Block unnecessary resources for performance optimization
            await page.route('**/*', (route) => {
                const resourceType = route.request().resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    route.abort();
                } else {
                    route.continue();
                }
            });
            
            // Navigate with optimized wait strategy
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Wait a bit for dynamic content to load
            await page.waitForTimeout(1000);
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            if (context) await context.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    // Launch browser with performance optimizations
    const browser = await chromium.launch({
        headless: true,
        proxy: PROXY_CONFIG,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        // Process URLs in batches to control concurrency
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/search?q=kids+shoes&options%5Bprefix%5D=last',
    ];

    console.log('Starting concurrent scraping with NodeJS Playwright-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

// Run the scraper if this file is executed directly
if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };