/**
 * Generated by: ScrapeOps AI Scraper Generator on 2026-02-17
 * Signup For Free Beta: https://scrapeops.io/app/register/ai-scraper-generator
 * Docs & Updates: https://scrapeops.io/docs/ai-scraper-generator
 * For Support & Feedback Email: ai-scraper-generator@scrapeops.io
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const cheerio = require('cheerio');
const fs = require('fs');
const { promisify } = require('util');

// Add stealth plugin
puppeteer.use(StealthPlugin());

const API_KEY = 'YOUR-API_KEY';

/**
 * Generate output filename with current timestamp
 * @returns {string} Output filename
 */
function generateOutputFilename() {
    const now = new Date();
    const timestamp = now.getFullYear().toString() +
        (now.getMonth() + 1).toString().padStart(2, '0') +
        now.getDate().toString().padStart(2, '0') + '_' +
        now.getHours().toString().padStart(2, '0') +
        now.getMinutes().toString().padStart(2, '0') +
        now.getSeconds().toString().padStart(2, '0');
    return 'decathlon_com_product_search_page_scraper_data_' + timestamp + '.jsonl';
}

// ScrapeOps Residential Proxy Configuration
const PROXY_SERVER = 'residential-proxy.scrapeops.io';
const PROXY_PORT = '8181';
const PROXY_USERNAME = 'scrapeops';
const PROXY_PASSWORD = API_KEY;

// Configuration
const CONFIG = {
    maxRetries: 3,
    maxConcurrency: 1,
    timeout: 180000,
    outputFile: generateOutputFilename()
};

/**
 * Data pipeline for handling scraped data
 */
class DataPipeline {
    constructor(outputFile = CONFIG.outputFile) {
        this.itemsSeen = new Set();
        this.outputFile = outputFile;
        this.writeFile = promisify(fs.appendFile);
    }

    isDuplicate(data) {
        const itemKey = JSON.stringify(data);
        if (this.itemsSeen.has(itemKey)) {
            console.warn('Duplicate item found, skipping');
            return true;
        }
        this.itemsSeen.add(itemKey);
        return false;
    }

    async addData(scrapedData) {
        if (!this.isDuplicate(scrapedData)) {
            try {
                const jsonLine = JSON.stringify(scrapedData) + '\n';
                await this.writeFile(this.outputFile, jsonLine, 'utf8');
                console.log('Saved item to', this.outputFile);
            } catch (error) {
                console.error('Error saving data:', error);
            }
        }
    }
}

/**
 * Extract structured data from HTML using Cheerio
 * @param {Object} $ - Cheerio instance
 * @param {string} url - Source URL
 * @returns {Object|null} - Extracted data or null
 */
function extractData($, url) {
    try {
        const domain = "https://www.decathlon.com";

        const makeAbsoluteURL = (urlStr) => {
            if (!urlStr) return "";
            if (urlStr.startsWith("http://") || urlStr.startsWith("https://")) return urlStr;
            if (urlStr.startsWith("//")) return "https:" + urlStr;
            if (urlStr.startsWith("/")) return domain + urlStr;
            return domain + "/" + urlStr;
        };

        const detectCurrency = (priceText) => {
            if (!priceText) return "USD";
            const text = priceText.toUpperCase();
            const currencyMap = {
                "USD": "USD", "US$": "USD", "US $": "USD", "$": "USD",
                "EUR": "EUR", "€": "EUR",
                "GBP": "GBP", "£": "GBP", "GB£": "GBP",
                "JPY": "JPY", "¥": "JPY", "JP¥": "JPY",
                "CAD": "CAD", "CA$": "CAD", "C$": "CAD",
                "AUD": "AUD", "AU$": "AUD", "A$": "AUD",
                "CNY": "CNY", "CN¥": "CNY", "RMB": "CNY",
                "CHF": "CHF", "FR.": "CHF",
                "SEK": "SEK", "KR": "SEK",
                "NZD": "NZD", "NZ$": "NZD",
            };
            for (const [code, currency] of Object.entries(currencyMap)) {
                if (text.includes(code)) return currency;
            }
            return "USD";
        };

        const parseNumericPrice = (priceText) => {
            if (!priceText) return 0;
            const cleanText = priceText.replace(/,/g, '');
            const match = cleanText.match(/[\d,]+\.?\d*/);
            return match ? parseFloat(match[0]) : 0;
        };

        const products = [];

        $("li.grid__item").each((i, el) => {
            const s = $(el);
            const product = {};

            // Name
            let name = s.find("h3.card__heading a").first().text();
            if (!name) name = s.find(".full-unstyled-link").first().text();
            name = name.trim();

            // URL
            let pUrl = s.find("h3.card__heading a").attr("href") || s.find("a.full-unstyled-link").attr("href") || "";
            pUrl = makeAbsoluteURL(pUrl);

            // ID
            let pId = "";
            let idAttr = s.find("h3.card__heading").attr("id") || s.find("a[id*='--']").first().attr("id") || "";
            if (idAttr.includes("--")) {
                const parts = idAttr.split("--");
                pId = parts[parts.length - 1];
            }

            if (!pId && pUrl) {
                const parts = pUrl.split("-");
                if (parts.length > 0) {
                    const lastPart = parts[parts.length - 1];
                    pId = lastPart.split("?")[0];
                }
            }

            // Images
            const images = [];
            const imgTag = s.find("div.media img").first();
            const imgUrl = imgTag.attr("src");
            const imgAlt = imgTag.attr("alt");
            if (imgUrl) {
                images.push({
                    altText: imgAlt || "",
                    url: makeAbsoluteURL(imgUrl)
                });
            }

            // Price Logic
            let currentPrice = 0;
            let preDiscountPrice = null;
            const priceContainer = s.find(".price").first();
            const isOnSale = priceContainer.hasClass("price--on-sale");

            if (isOnSale) {
                const saleText = priceContainer.find(".price-item--sale").first().text();
                currentPrice = parseNumericPrice(saleText);

                let regularText = priceContainer.find(".price__sale .price-item--regular").first().text();
                if (!regularText) {
                    regularText = priceContainer.find(".font-cap .price-item--regular").first().text();
                }
                const parsedPrePrice = parseNumericPrice(regularText);
                preDiscountPrice = parsedPrePrice > 0 ? parsedPrePrice : null;
            } else {
                let regularText = priceContainer.find(".price-item--regular").first().text();
                if (!regularText) {
                    regularText = priceContainer.find(".price__regular").text();
                }
                currentPrice = parseNumericPrice(regularText);
            }

            // Ratings
            let ratingValue = 0.0;
            let reviewCount = 0;
            const ratingText = s.find(".rating-text span").first().text().trim();
            const countText = s.find(".rating-count span").first().text().trim();
            if (ratingText) {
                ratingValue = parseFloat(ratingText) || 0.0;
            }
            if (countText) {
                const countVal = countText.replace(/[^\d]/g, "");
                reviewCount = parseInt(countVal, 10) || 0;
            }

            // Badges
            const badges = [];
            const seenBadges = new Set();
            s.find(".badge").each((j, b) => {
                const label = $(b).text().trim();
                if (label && !seenBadges.has(label)) {
                    badges.push({
                        imageUrl: null,
                        label: label,
                        type: "deal"
                    });
                    seenBadges.add(label);
                }
            });

            // Brand & Category
            let brand = s.find(".font-body-s").first().text().trim();
            if (!brand) brand = "Quechua";
            
            let category = "Shoes";
            if (name.toLowerCase().includes("boot")) {
                category = "Snow boots";
            }

            // Variants
            const visibleOptions = [];
            s.find(".swatch").each((j, swEl) => {
                const sw = $(swEl);
                visibleOptions.push({
                    imageUrl: makeAbsoluteURL(sw.attr("data-variant-image-src")),
                    type: "color/size",
                    value: sw.attr("data-variant-title")
                });
            });

            // Promotions
            const promotions = [];
            if (preDiscountPrice !== null) {
                const discountLabel = badges.length > 0 ? badges[0].label : "";
                let perc = 0;
                const mP = discountLabel.match(/(\d+)%/);
                if (mP) perc = parseInt(mP[1], 10);
                
                promotions.push({
                    description: discountLabel,
                    discountPercentage: perc,
                    endDate: null,
                    type: "discount"
                });
            }

            // Schema mapping
            products.push({
                aggregateRating: {
                    bestRating: 5,
                    ratingValue: ratingValue,
                    reviewCount: reviewCount,
                    worstRating: null
                },
                availability: "in_stock",
                availabilityMessage: null,
                badges: badges,
                brand: brand,
                category: category,
                currency: detectCurrency(s.find(".price-item--regular").first().text()),
                description: null,
                images: images,
                isSponsored: false,
                keyFeatures: [],
                name: name,
                preDiscountPrice: preDiscountPrice,
                price: currentPrice,
                priceRange: null,
                productId: pId,
                promotions: promotions,
                seller: null,
                shipping: null,
                url: pUrl,
                variants: {
                    variantCount: null,
                    visibleOptions: visibleOptions
                },
                additionalImages: []
            });
        });

        const searchMeta = {
            query: $("input[name='q']").first().val() || "kids shoes",
            resultsDisplayed: products.length,
            searchType: "keyword",
            searchUrl: domain + "/search?q=kids+shoes&options%5Bprefix%5D=last",
            totalResults: 7
        };

        return {
            breadcrumbs: null,
            pagination: {
                currentPage: 1,
                hasNextPage: false,
                hasPreviousPage: false,
                nextPageUrl: null,
                previousPageUrl: null,
                totalPages: 1
            },
            products: products,
            recommendations: null,
            relatedSearches: [],
            searchMetadata: searchMeta,
            sponsoredProducts: []
        };
    } catch (error) {
        console.error('Error extracting data:', error);
        return null;
    }
}

/**
 * Scrape a single page with retry logic using Puppeteer with stealth
 * @param {string} url - URL to scrape
 * @param {DataPipeline} pipeline - Data pipeline instance
 * @param {Object} browser - Puppeteer browser instance
 * @param {number} retries - Number of retries
 */
async function scrapePage(url, pipeline, browser, retries = CONFIG.maxRetries) {
    let success = false;
    let attempts = 0;

    while (attempts <= retries && !success) {
        let page = null;
        
        try {
            page = await browser.newPage();
            
            // Set viewport
            await page.setViewport({ width: 1920, height: 1080 });
            
            // Set user agent
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36');
            
            // Block unnecessary resources for performance optimization
            await page.setRequestInterception(true);
            page.on('request', (request) => {
                const resourceType = request.resourceType();
                if (['image', 'media', 'font', 'stylesheet'].includes(resourceType)) {
                    request.abort();
                } else {
                    request.continue();
                }
            });
            
            // Authenticate with proxy
            await page.authenticate({
                username: PROXY_USERNAME,
                password: PROXY_PASSWORD
            });
            
            // Navigate with optimized wait strategy
            await page.goto(url, { 
                waitUntil: 'domcontentloaded',
                timeout: CONFIG.timeout 
            });
            
            // Wait for product grid elements to be present
            await page.waitForSelector('li.grid__item', { timeout: 10000 }).catch(() => {});
            
            const bodyHTML = await page.evaluate(() => document.body.innerHTML);
            const $ = cheerio.load(bodyHTML);
            
            const scrapedData = extractData($, url);
            
            if (scrapedData) {
                await pipeline.addData(scrapedData);
                success = true;
                console.log('Successfully scraped:', url);
            } else {
                console.warn('No data extracted from:', url);
            }
        } catch (error) {
            console.error('Exception scraping', url, ':', error.message);
            
            if (attempts < retries) {
                const delay = Math.pow(2, attempts) * 1000;
                console.log('Retrying in', delay, 'ms...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        } finally {
            if (page) await page.close();
            attempts++;
        }
    }

    if (!success) {
        console.error('Failed to scrape', url, 'after', retries, 'retries');
    }
}

/**
 * Scrape multiple URLs concurrently with controlled concurrency
 * @param {string[]} urls - Array of URLs to scrape
 */
async function concurrentScraping(urls) {
    const pipeline = new DataPipeline(CONFIG.outputFile);
    
    // Launch browser with performance optimizations
    const browser = await puppeteer.launch({
        headless: 'new',
        ignoreHTTPSErrors: true,
        args: [
            `--proxy-server=http://${PROXY_SERVER}:${PROXY_PORT}`,
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--disable-web-security'
        ]
    });

    try {
        // Process URLs in batches to control concurrency
        for (let i = 0; i < urls.length; i += CONFIG.maxConcurrency) {
            const batch = urls.slice(i, i + CONFIG.maxConcurrency);
            const promises = batch.map(url => scrapePage(url, pipeline, browser, CONFIG.maxRetries));
            
            try {
                await Promise.all(promises);
                console.log('Completed batch', Math.floor(i / CONFIG.maxConcurrency) + 1, 'of', Math.ceil(urls.length / CONFIG.maxConcurrency));
            } catch (error) {
                console.error('Error in batch processing:', error);
            }
        }
    } finally {
        await browser.close();
    }
}

/**
 * Main execution function
 */
async function main() {
    const urls = [
        'https://www.decathlon.com/search?q=kids+shoes&options%5Bprefix%5D=last',
    ];

    console.log('Starting concurrent scraping with NodeJS Puppeteer-Extra + Stealth...');
    console.log('URLs to scrape:', urls.length);
    console.log('Max concurrency:', CONFIG.maxConcurrency);
    console.log('Output file:', CONFIG.outputFile);

    try {
        await concurrentScraping(urls);
        console.log('Scraping completed successfully!');
    } catch (error) {
        console.error('Scraping failed:', error);
        process.exit(1);
    }
}

// Run the scraper if this file is executed directly
if (require.main === module) {
    main().catch(console.error);
}

module.exports = { extractData, scrapePage, concurrentScraping, DataPipeline };